/*
 * This source file was generated by the Gradle 'init' task
 */
package factorial;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Scanner scanIn = new Scanner(System.in);

        System.out.print("Hey You! enter me: ");
        int number = scanIn.nextInt();
        scanIn.close();

        long factorial = 1;
        System.out.println("Enter a number: " + number);
        for (int i = 1; i <= number; i++) {
            System.out.println(i + " ! = " + factorial);
            factorial += factorial * i;
        }
    }
}
