/*
 * This source file was generated by the Gradle 'init' task
 */
package p.xor.q;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello My homework";
    }

    public static void main(String[] args) {
        Scanner scanIn = new Scanner(System.in);
        System.out.print("Input P:");
        int p = scanIn.nextInt();
        System.out.print("Input Q:");
        int q = scanIn.nextInt();
        scanIn.close();
        if ((p == 0 || p == 1) && (q == 0 || q == 1)) {
            if (p == q) {
                System.out.println(p + " XOR " + q + " = " + 0);
            } else {
                System.out.println(p + " XOR " + q + " = " + 1);
            }
        } else {
            System.out.println("!!! Only 1 or 0 !!!");
        }

    }
}