/*
 * This source file was generated by the Gradle 'init' task
 */
package welfare;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello My homework";
    }

    public static void main(String[] args) {
        Scanner scanIn = new Scanner(System.in);
        System.out.print("Input your salary: ");
        float salary = scanIn.nextFloat();
        scanIn.close();
        float welfare = 0;
        if (salary <= 15000) {
            welfare += salary * 0.05;
        } else {
            welfare += 15000 * 0.05;
        }
        System.out.printf("Your Welfare is: %.2f Baht\n", welfare);
    }
}